### ISSUE TITLE
Pollard Rho kangaroo Solved

### ISSUE THREAD

**Issue by Saadinr** [beranm14/pollard_rho#3]
Pollard Rho kangaroo Solved Cuda Windows 10, Linux https://github.com/Saadinr/Pollard-s

**Comment by ZielarSRC** [comment]
**Your mother** is solved!
Fuck her in the ass and all your fucking family. And I wish you would die, twat!

**Comment by ZielarSRC** [comment]
> Pollard Rho kangaroo Solved Cuda Windows 10, Linux https://github.com/Saadinr/Pollard-s

**### Your mother is solved!**
Fuck her in the ass and all your fucking family. And I wish you would die, twat!

**Comment by beranm14** [comment]
I am not sure my old solution of some university homework deserves a discussion about somebody's mother :-D
